version: '2.1'
services:
    worker:
        image: mobifone/docker-airflow:latest
        container_name: mobifone-airflow_worker_${WORKER_HOST}
        restart: always
        hostname: ${WORKER_HOST}
        ports:
            - 8793:8793
        volumes:
            - ${PATH_CODE}/dags:/usr/local/airflow/dags
            - ${PATH_CODE}/plugins:/usr/local/airflow/plugins
            - ${PATH_DATA}/data:/usr/local/airflow/data
        environment:
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - AIRFLOW__CELERY__BROKER_URL=redis://${MASTER_HOST}:9736/1
            - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@${MASTER_HOST}:54325/airflow
            - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://airflow:airflow@${MASTER_HOST}:54325/airflow
            #- AIRFLOW__CORE__HOSTNAME_CALLABLE=airflow.hostname_resolver:resolve
        entrypoint: airflow worker -cn worker_${WORKER_HOST}
        healthcheck:
            test: [ "CMD-SHELL", "[ -f /usr/local/airflow/airflow-worker.pid ]" ]
            interval: 30s
            timeout: 30s
            retries: 3